"""Prior recovery from a trained convex potential psi_theta.

Two routes (see the numerics audit):

  Route 1 (inversion baseline, kept per decision D1): invert psi_theta at query
    points x to get y with grad psi(y) = x, then evaluate the prior via the
    Fenchel identity J(x) = <x, y> - psi(y) - 0.5||x||^2.

  Route 2 (the reported method): sample the conjugate pairs generated by the
    first network and fit a second network G whose potential is psi* + 0.5||.||^2,
    so that J(x) = G(x) - 0.5||x||^2.

Because psi(y) = (J + 0.5||.||^2)*(y), both routes recover the SAME prior; Route
1 is only a baseline.

FIX (Phase 1, finding 1): Route-1 recovery used 0.5*||x|| instead of
0.5*||x||^2. The correct Fenchel term is quadratic.
"""
import numpy as np
import torch

from .invert import invert


def euclid_norm_sq(x):
    if x.ndim == 1:
        return np.sum(x * x)
    return np.sum(x * x, axis=1)


def cvx(x, model):
    """Learned convex potential psi_theta(x) as a numpy array of shape (n,)."""
    device = next(model.parameters()).device
    xt = torch.tensor(np.asarray(x)).float().to(device)
    return model.scalar(xt).squeeze(1).detach().cpu().numpy()


def prox(x, model):
    """Learned proximal map grad psi_theta(x) as a numpy array of shape (n, dim)."""
    device = next(model.parameters()).device
    xt = torch.tensor(np.asarray(x)).float().to(device)
    return model(xt).detach().cpu().numpy()


# ----------------------------- Route 1 --------------------------------------
def evaluate_learned_prior(x, y, model):
    """J(x) = <x, y> - psi(y) - 0.5||x||^2, with y = (grad psi)^{-1}(x).

    FIX: the 0.5*||x||^2 term was previously 0.5*||x|| (finding 1).
    """
    psi_y = cvx(y, model)
    return np.sum(x * y, axis=1) - 0.5 * euclid_norm_sq(x) - psi_y


def recover_prior_route1(x, model, inv_alg="cvx_gd", return_preimage=False, **kwargs):
    """Full Route-1 recovery at query points x. ``kwargs`` may carry ``alpha``."""
    y = invert(x, model, inv_alg, **kwargs)
    J = evaluate_learned_prior(x, y, model)
    return (J, y) if return_preimage else J


# --------------- symmetric, ground-truth-free certificates -------------------
# Both routes produce a candidate preimage y(x) of the query x:
#   Route 1: y = argmin_y psi(y) + (alpha/2)||y||^2 - <x,y>   (an optimization)
#   Route 2: y = grad G(x)                                    (one forward pass)
# because G ~= psi*, so grad G = (grad psi)^{-1}. The SAME two checks then apply
# to both, using only psi_theta and G_theta -- never the ground truth. This is
# the answer to "can we double-check Route 2 as well": yes, and with Route 1's
# own certificate, so neither route gets a privileged diagnostic.


def prox_residual(x, y, model):
    """||grad psi(y) - x|| / max(1, ||x||), per query point.

    Zero iff y is an exact preimage of x under the LEARNED psi. For an exact
    alpha-regularized Route-1 solve this equals alpha*||y||/max(1,||x||), so the
    residual reports the regularizer's distortion rather than concealing it.
    """
    x = np.asarray(x)
    gpsi = prox(y, model)  # grad psi(y)
    num = np.linalg.norm(gpsi - x, axis=1)
    return num / np.maximum(1.0, np.linalg.norm(x, axis=1))


def route2_preimage(x, model_G):
    """y = grad G(x), Route 2's implied preimage. G ~= psi* => grad G = (grad psi)^-1."""
    return prox(x, model_G)


def fenchel_young_gap(x, y, model, model_G):
    """psi(y) + G(x) - <x,y>, which is >= 0 for a true conjugate pair and 0 iff
    x in d psi(y). Measures how far (psi_theta, G_theta) are from conjugate."""
    x, y = np.asarray(x), np.asarray(y)
    return cvx(y, model) + cvx(x, model_G) - np.sum(x * y, axis=1)


def route_report(J, J_true, x, y, model, model_G):
    """Identical report for either route. ``y`` is that route's preimage.

    ``rmse`` is unconditional -- every query point, no abstention, for both
    routes. The certificates are diagnostics reported alongside it, never a
    licence to drop points from the error.
    """
    err = np.asarray(J) - np.asarray(J_true)
    r = prox_residual(x, y, model)
    fy = fenchel_young_gap(x, y, model, model_G)
    return {
        "rmse": float(np.sqrt(np.mean(err**2))),
        "median_prox_residual": float(np.median(r)),
        "p90_prox_residual": float(np.percentile(r, 90)),
        "median_fy_gap": float(np.median(fy)),
        "max_preimage_linf": float(np.max(np.abs(np.asarray(y)))),
        "n_points": int(err.size),
    }


# ----------------------------- Route 2 --------------------------------------
def conjugate_samples(x_k, model):
    """Generate Route-2 training pairs (y_k, G_k) from the first network.

    y_k = grad psi(x_k),  G_k = <y_k, x_k> - psi(x_k)  (a sample of psi*(y_k)),
    exact because y_k = grad psi(x_k) attains the sup defining psi*.

    One forward + one backward: the old version called model.scalar(x_k) and then
    model(x_k), and the latter recomputes scalar internally, so psi was evaluated
    twice per call.
    """
    device = next(model.parameters()).device
    xk = torch.tensor(np.asarray(x_k)).float().to(device).requires_grad_(True)
    psi_xk = model.scalar(xk)
    yk = torch.autograd.grad(psi_xk.sum(), xk)[0]
    Gk = torch.sum(yk * xk, dim=1, keepdim=True) - psi_xk
    return (
        yk.detach().cpu().numpy(),
        Gk.detach().cpu().numpy(),
    )


def evaluate_learned_prior_G(x, model_G):
    """Route-2 recovery: J(x) = G(x) - 0.5||x||^2."""
    G_x = cvx(x, model_G)
    return G_x - 0.5 * euclid_norm_sq(np.asarray(x))
